CheeseMVC/ViewModels/UserSignupLoginViewModel.cs
using System;
using CheeseMVC.ViewModels;

namespace CheeseMVC.ViewModels
{
    public class UserSignupLoginViewModel
    {
        public AddUserViewModel AddUserVM { get; set; }
        public LoginUserViewModel LoginUserVM { get; set; }

        public UserSignupLoginViewModel()
        {
        }
    }
}

CheeseMVC/Controllers/UserSignupLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CheeseMVC.Data;
using CheeseMVC.Models;
using CheeseMVC.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CheeseMVC.Controllers
{
    public class UserSignupLoginController : Controller
    {
        // this private field allows controller to access the database and sets up identity
        private readonly CheeseDbContext context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public UserSignupLoginController(CheeseDbContext dbContext,
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager)
        {
            context = dbContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddUser(UserSignupLoginViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var newUser = new IdentityUser
                {
                    UserName = vm.AddUserVM.Username,
                    Email = vm.AddUserVM.Email
                };

                var result = await _userManager.CreateAsync(newUser, vm.AddUserVM.Password);

                if (result.Succeeded)
                {
                    var uzer = await _userManager.FindByNameAsync(vm.AddUserVM.Username);

                    if (uzer != null)
                    {
                        var signInResult = await _signInManager.PasswordSignInAsync(uzer, vm.AddUserVM.Password, false, false);
                        if (signInResult.Succeeded)
                        {
                            return Redirect("/Category");
                        }
                    }
                }
            }
            return View("Index", vm);
        }

        [HttpPost]
        public async Task<IActionResult> LoginUser(UserSignupLoginViewModel vm)
        {

            var uzer = await _userManager.FindByNameAsync(vm.LoginUserVM.Username);

            if (uzer != null)
            {
                var signInResult = await _signInManager.PasswordSignInAsync(uzer, vm.LoginUserVM.Password, false, false);
                if (signInResult.Succeeded)
                {
                    return Redirect("/Category");
                }
            }

            return View("Index", vm);
        }

        public async Task<IActionResult> LogoutUser()
        {
            await _signInManager.SignOutAsync();

            return Redirect("/UserSignupLogin/Index");
        }
    }
}

CheeseMVC/Views/UserSignupLogin/Index.cshtml
@model CheeseMVC.ViewModels.UserSignupLoginViewModel

<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="jumbotron bg-danger">
                <h1 class="text-light text-center">About Foodoku</h1>
                <p class="lead text-light">this will be a paragraph that describes the app</p>
            </div>
        </div>
        <div class="col-6">
                <div class="row">
                    <div class="card">
                        <h3 class="card-header bg-primary text-light text-center">Login</h3>
                        <div class="card-body">
                            <form asp-controller="UserSignupLogin" asp-action="LoginUser" method="post">
                                <div class="card-text row form-group form-inline">
                                    <label asp-for="@Model.LoginUserVM.Username" class="col-4 col-form-label">Username</label>
                                    <input asp-for="@Model.LoginUserVM.Username" type="text" class="form-control" placeholder="Username" />
                                    <span asp-validation-for="@Model.LoginUserVM.Username" class="text-danger"></span>
                                    <label asp-for="@Model.LoginUserVM.Password" class="col-4 col-form-label">Password</label>
                                    <input type="password" asp-for="@Model.LoginUserVM.Password" class="form-control" placeholder="Password">
                                    <span asp-validation-for="@Model.LoginUserVM.Password" class="text-danger"></span>
                                </div>
                                <div class="row">
                                    <div class="card-text col-12 text-center">
                                        <button type="submit" class="btn btn-primary">Login</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="card">
                        <h3 class="card-header bg-secondary text-dark text-center">Sign Up</h3>
                        <div class="card-body">
                            <form asp-controller="UserSignupLogin" asp-action="AddUser" method="post">
                                <div class="card-text row form-group form-inline">
                                    <label asp-for="@Model.AddUserVM.Username" class="col-4 col-form-label">Username </label>
                                    <input asp-for="@Model.AddUserVM.Username" type="text" class="form-control" placeholder="Username">
                                    <span asp-validation-for="@Model.AddUserVM.Username" class="text-danger"></span>
                                    <label asp-for="@Model.AddUserVM.Email" class="col-4 col-form-label">Email</label>
                                    <input type="text" asp-for="@Model.AddUserVM.Email" class="form-control" placeholder="Email" />
                                    <span asp-validation-for="@Model.AddUserVM.Email" class="text-danger"></span>
                                    <label asp-for="@Model.AddUserVM.Password" class="col-4 col-form-label">Password</label>
                                    <input type="password" asp-for="@Model.AddUserVM.Password" class="form-control" placeholder="Password">
                                    <span asp-validation-for="@Model.AddUserVM.Password" class="text-danger"></span>
                                    <label asp-for="@Model.AddUserVM.Verify" class="col-4 col-form-label">Verify Password</label>
                                    <input type="password" asp-for="@Model.AddUserVM.Verify" class="form-control" placeholder="Verify Password">
                                    <span asp-validation-for="@Model.AddUserVM.Verify" class="text-danger"></span>
                                </div>
                                <div class="row">
                                    <div class="card-text col-12 text-center">
                                        <button type="submit" class="btn btn-secondary">Sign Up</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</div>



CheeseMVC/Views/UserSignupLogin/Success.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>SUCCESS!!!!</h1>